name: Multiverse-CoreFix
version: 1.2
main: me.francesco.multiversecorefix.MultiverseCoreFix
authors: [Pompiere1]
description: A simple add-on for fix the latest known bug for Multiverse-Core
softdepend: [Multiverse-Core]
commands:
  mvcfix:
    aliases: [mvcf, multiverse-corefix, multiversecorefix]
    description: Main command
